#!/bin/bash
GVT_PCI=0000:00:02.0
GVT_GUID=af5972fb-5530-41a7-0000-fd836204445b
MDEV_TYPE=i915-GVTg_V5_4
DOMAIN1=Windows_10-GVTg
DOMAIN2=ubuntu20.04
if [ $# -ge 3 ]; then
    if { [ "$1" = "$DOMAIN2" ] || [ "$1" = "$DOMAIN1" ]; } && [ "$2" = "prepare" ] && [ "$3" = "begin" ]; then
        #virsh net-start default-docker
        echo "$GVT_GUID" > "/sys/bus/pci/devices/$GVT_PCI/mdev_supported_types/$MDEV_TYPE/create"
    elif { [ "$1" = "$DOMAIN2" ] || [ "$1" = "$DOMAIN1" ]; } && [ "$2" = "release" ] && [ "$3" = "end" ]; then
        echo 1 > /sys/bus/pci/devices/"$GVT_PCI"/"$GVT_GUID"/remove
        #sleep 1
        #virsh net-destroy default-docker
    fi
fi
